server:
    port: ${SERVER_PORT:8080}

microservices:
    user-service:
        url: ${USER_SERVICE_URL}
    game-service:
        url: ${GAME_SERVICE_URL}
    friendship-service:
        url: ${FRIENDSHIP_SERVICE_URL}
    product-service:
        url: ${PRODUCT_SERVICE_URL}
    message-service:
        url: ${MESSAGE_SERVICE_URL}
    auth-service:
        url: ${AUTH_SERVICE_URL}
    match-service:
        url: ${MATCH_SERVICE_URL}

spring: 
    config:
        import: optional:file:.env[.properties]

springdoc:
    swagger-ui:
        config-url: /v3/api-docs/swagger-config
        urls[0]:
            name: Auth service
            url: /docs/authservice/v3/api-docs
        urls[1]:
            name: Game service
            url: /docs/gameservice/v3/api-docs
        urls[2]:
            name: User service
            url: /docs/userservice/v3/api-docs
        urls[3]:
            name: Product service
            url: /docs/productservice/v3/api-docs
        urls[4]:
            name: Game service
            url: /docs/gameservice/v3/api-docs
        urls[5]:
            name: Friendship service
            url: /docs/friendshipservice/v3/api-docs
        urls[6]:
            name: Message service
            url: /docs/messageservice/v3/api-docs
        urls[7]:
            name: Match service
            url: /docs/matchservice/v3/api-docs

security:
    excluded:
        urls: /swagger-ui.html, /swagger-ui/**, /docs/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**, /webjars/**

jwt:
    access:
        public: ${JWT_ACCESS_PUBLIC}
    refresh:
        public: ${JWT_REFRESH_PUBLIC}
