server:
    port: ${SERVER_PORT:8080}

microservices:
    user-service:
        url: ${USER_SERVICE_URL}
    game-service:
        url: ${GAME_SERVICE_URL}
    friendship-service:
        url: ${FRIENDSHIP_SERVICE_URL}

jwt:
    access:
        public: ${JWT_ACCESS_PUBLIC}
    refresh:
        public: ${JWT_REFRESH_PUBLIC}
