server:
    port: ${SERVER_PORT:8080}

microservices:
    user-service:
        url: ${USER_SERVICE_URL}
    game-service:
        url: ${GAME_SERVICE_URL}
    friendship-service:
        url: ${FRIENDSHIP_SERVICE_URL}
    product-service:
        url: ${PRODUCT_SERVICE_URL}
    message-service:
        url: ${MESSAGE_SERVICE_URL}
    auth-service:
        url: ${AUTH_SERVICE_URL}

# springdoc:
#     swagger-ui:
#         enabled: true
#         path: /swagger-ui.html
#         urls:
#             - name: Auth service
#               url: /docs/authservice/v3/api-docs

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls[0]:
            name: Auth service
            url: /docs/authservice/v3/api-docs

security:
    excluded:
        urls: /swagger-ui.html, /swagger-ui/**, /docs/**, /v3/api-docs/**, /swagger-resources/**, /api-docs/**, /webjars/**

jwt:
    access:
        public: ${JWT_ACCESS_PUBLIC}
    refresh:
        public: ${JWT_REFRESH_PUBLIC}
